DROP TABLE IF EXISTS schema_version;

DROP TABLE IF EXISTS Spectator;
DROP TABLE IF EXISTS Seat;
DROP TABLE IF EXISTS Tribune;
DROP TABLE IF EXISTS Matchs;
DROP TABLE IF EXISTS Plays_In;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Athletic;
DROP TABLE IF EXISTS Lap;
DROP TABLE IF EXISTS Race;
DROP TABLE IF EXISTS Refreshment;